sgawards/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('auth/', include('userlogin.urls')),
    path('panelist/', include('panelists.urls')),
    path('test/', include('testjs.urls'))
]

user/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('nominate/', views.nominate, name='nominate'),
    path('nomin/', views.nomin, name='nomin')
]

userlogin/urls.py
from django.urls import  path
from . import views

app_name='auth'
urlpatterns = [
    path('login/', views.loginuser,name='login'),
    path('logout/', views.logout_user,name='logoutuser')
    ]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Home</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'user/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'user/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'user/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'user/css/sidebar.css' %}">
    <link rel="stylesheet" href="{% static 'user/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'user/css/font-awesome.css' %}">
    <style>
        .nav-item :hover {
            color: springgreen !important;
            border-top-style: dotted;
            border-right-style: solid;
            border-bottom-style: dotted;
            border-left-style: solid;
            .navbar{
                background-color: #f8f9fa;
                color: blue;
            }
        }
        nav::before .abovenav{
            background-color: maroon;
            margin-top: 0;
            padding:12px;
        }
    </style>
</head>
<body style="background-color: #cce5ff">
<nav class="navbar navbar-expand-md bg-dark navbar-dark fixed-top">
    <!-- Brand -->
    <a class="navbar-brand" style="color:cadetblue;font-size: 24px;" href="#">STAFF RECOGNITION AWARDS</a>

    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Navbar links -->
    {% if user.is_authenticated %}
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav mx-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">HOME</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'nominate' %}">NOMINATIONS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">HISTORY</a>
            </li>
        </ul>
        <ul class="navbar-nav">
        <li class="nav-item">
            <a href="#" class="nav-link logout" style="text-transform: uppercase"><i class="fa-user"></i> <span>{{ user.username }}</span></a>
            </li>
            <li class="nav-item">
                <a href="{% url 'auth:logoutuser' %}" class="nav-link logout">LOG OUT</a>
            </li>
        </ul>
        {% else %}
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="#" class="nav-link logout">LOG OUT</a>
            </li>
        </ul>
        {% endif %}
    </div>
</nav>
<br>
{% block content %}

{% endblock %}

<!-- jQuery CDN -->
<script src="{% static 'user/js/jquery/jquery-2.2.4.min.js' %}"></script>
<script src="{% static 'jquery-ui/jquery-ui.min.css' %}"></script>
<script src="{% static 'jquery-ui/external/jquery/jquery.js' %}"></script>
<script src="{% static 'jquery-ui/jquery-ui.min.js' %}"></script>
<script src="{% static 'user/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'user/bootstrap/js/bootstrap.bundle.js' %}"></script>
<script src="{% static 'user/bootstrap/js/bootstrap.js' %}"></script>



</body>
</html>